race_code = ('雅族', '含族', '闪族', '蛮族')
work_code = ('战士', '法师', '牧师', '盗贼')
sex_code = ('男性', '女性', '无性')
point_code = {'w': '北方死沼泽', 's': '南方幽暗林', 'a': '西方梦之丘', 'd': '东方昆仑墟'}
menu = {1: '显示状态', 2: '检查装备', 3: '进入地图', 4: '存档', 5: '退出Lost', 6: '版本演化史'}
po = (0, 0)
_path = 'name/'
map_x = [i for i in range(-9, 10)]
map_y = [j for j in range(-9, 10)]
mmap = []
